name: Docker Image CI
on: 
  push:
    branches:
      - "main"
      - "feature/*"
      
jobs:

  Build_Stage:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gallery

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.TEMP_REGISTRY_USERNAME }}
          password: ${{ secrets.TEMP_REGISTRY_PASSWORD }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 

      - name: show path
        run: |
          pwd
          ls -a 

      - run: |
          docker build . -t ${{ secrets.TEMP_REGISTRY_LOGIN_SERVER }}/dstoolkitaiux:latest |  docker push ${{ secrets.TEMP_REGISTRY_LOGIN_SERVER }}/dstoolkitaiux:latest
         

  # Deploy_Stage:
  #   runs-on: ubuntu-latest
  #   needs: Build_Stage
  #   environment:
  #     name: 'production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #   - name: Deploy to Azure Web App
  #     id: deploy-to-webapp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'app-aigallery-dev-001'
  #       slot-name: 'production'
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #       images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/dstoolkitaiux:latest'